### ISSUE TITLE
support for cmd-W to close?

### ISSUE THREAD

**Issue by jbclements** [tonyg/racket-explorer#10]
I often accideliberately insert `(explore z)` in a place in the code that causes thirty windows to be opened in rapid succession. It appears to me that hitting cmd-w (or, presumably, ctl-w on other platforms) does not close the window. It would be *so awesome* if this were the case....

**Comment by tonyg** [comment]
There's one niggle with this patch: the default editor keybindings on Unix are :m:w, :c:w, :c:y for copy, cut and paste, while on Windows they are :c:x, :c:c, :c:v. This patch sets :c:w for both Windows and Unix to close the window, interfering with the emacs-style cut binding on Unix. I can't think of a good way to resolve the conflict. Any thoughts?
